reminder/note/urls.py
from django.conf.urls import url

urlpatterns = [

    url(r'^$', 'note.views.all', name='all'),

    url(r'^add/$', 'note.views.addNote', name='add'),
    url(r'^addCat/$', 'note.views.addCat', name='addCat'),
    url(r'^addTag/$', 'note.views.addTag', name='addTag'),

    url(r'^editTag/(?P<tag_id>[0-9]+)/$', 'note.views.addTag', name='editTag'),
    url(r'^edit/(?P<note_id>[0-9]+)/$', 'note.views.addNote', name='editNote'),
    url(r'^editCat/(?P<cat_id>[0-9]+)/$', 'note.views.addCat', name='editCat'),

    url(r'^delNote/(?P<note_id>[0-9]+)/$', 'note.views.delNote', name='delNote'),
    url(r'^delCat/(?P<cat_id>[0-9]+)/$', 'note.views.delCat', name='delCat'),
    url(r'^delTag/(?P<tag_id>[0-9]+)/$', 'note.views.delTag', name='delTag'),

    url(r'^cat(?P<cat_id>[0-9]+)/$', 'note.views.all', name='showCat'),
    url(r'^tag(?P<tag_id>[0-9]+)/$', 'note.views.all', name='showTag'),

]

reminder/reminder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'reminder.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^$', 'reminder.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('authorization.urls', namespace='author')),
    url(r'^note/', include('note.urls', namespace='note')),
    url(r'^$', 'note.views.all', name='home'),
]

reminder/note/models.py
from django.db import models
from django.contrib.auth.models import User

from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.
class Colors(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


class Tags(models.Model):
    name = models.CharField(max_length=40)
    author = models.ForeignKey(User)

    def __unicode__(self):
        return self.name


class Categories(MPTTModel):
    name = models.CharField(max_length=100)
    parent = TreeForeignKey('self', blank=True, null=True, verbose_name="parent", related_name='child')
    author = models.ForeignKey(User)

    def __unicode__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']


class Notes(models.Model):
    name = models.CharField(max_length=100)
    context = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, editable=False)
    color = models.ForeignKey(Colors, blank=True, null=True)
    tag = models.ManyToManyField(Tags, blank=True)
    category = models.ManyToManyField(Categories, blank=True)
    author = models.ForeignKey(User)

    def __unicode__(self):
        return self.name

reminder/note/forms.py
from django import forms

from .models import Notes, Tags, Categories

from mptt.forms import TreeNodeChoiceField


class AddNoteForm(forms.ModelForm):

    # category = TreeNodeChoiceField(queryset=Categories.objects.none(), required=False)
    # tag = forms.ModelChoiceField(queryset=Tags.objects.none(), required=False)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(AddNoteForm, self).__init__(*args, **kwargs)
        self.fields['tag'].queryset = Tags.objects.filter(author=user)
        self.fields['category'].queryset = Categories.objects.filter(author=user)
        self.fields['category'].level_indicator = unichr(0x00A0) * 2

    class Meta:
        model = Notes
        fields = ['name', 'context', 'color', 'tag', 'category']


class AddTagForm(forms.ModelForm):

    class Meta:
        model = Tags
        fields = ['name']

    def __init__(self, user, *args, **kwargs):
        super(AddTagForm, self).__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        note = super(AddTagForm, self).save(commit=False)
        note.author_id = self.user
        if commit:
            note.save()
        return note


class AddCategoryForm(forms.ModelForm):

    parent = TreeNodeChoiceField(Categories.objects.none(), required=False)

    def __init__(self, user, is_disabled=None, *args, **kwargs):
        self.user = user
        super(AddCategoryForm, self).__init__(*args, **kwargs)
        self.fields['parent'].queryset = Categories.objects.filter(author=user)
        self.fields['parent'].level_indicator = unichr(0x00A0) * 2
        if is_disabled:
            self.fields['parent'].widget = forms.Select(attrs={'disabled': 'disabled'})

    class Meta:
        model = Categories
        fields = ['name', 'parent']

    def save(self, commit=True):
        note = super(AddCategoryForm, self).save(commit=False)
        note.author_id = self.user
        if commit:
            note.save()
        return note

reminder/note/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required

from .models import Notes, Categories, Tags
from .forms import AddNoteForm, AddTagForm, AddCategoryForm


@login_required(login_url='author:login')
def all(request, cat_id=None, tag_id=None):

    user = get_user(request)
    args = {}
    args['categories'] = Categories.objects.filter(author=user.id)
    args['all_tags'] = Tags.objects.filter(author=user.id)
    args['all_notes'] = Notes.objects.filter(author=user.id)
    args['form_note'] = AddNoteForm(user.id)
    args['form_tag'] = AddTagForm
    if cat_id:
        args['notes'] = Notes.objects.filter(author=user.id, category=cat_id)
    elif tag_id:
        args['notes'] = Notes.objects.filter(author=user.id, tag=tag_id)
    else:
        args['notes'] = args['all_notes']

    return render(request, 'note/all.html', args)


@login_required(login_url='author:login')
def addNote(request, note_id=None):

    user = get_user(request)
    args = {}
    args['categories'] = Categories.objects.filter(author=user.id)
    args['all_tags'] = Tags.objects.filter(author=user.id)
    if note_id:
        try:
            query = Notes.objects.get(pk=note_id, author=user.id)
        except Notes.DoesNotExist:
            return redirect(reverse('note:all'))
    else:
        query = None
    args['note_id'] = note_id
    args['form_note'] = AddNoteForm(user.id, instance=query)

    if request.POST:
        post_form = AddNoteForm(user.id, data=request.POST, instance=query)
        if post_form.is_valid():
            temp_save = post_form.save(commit=False)
            temp_save.author_id = user.id
            temp_save.save()
            post_form.save_m2m()
            return redirect(reverse('note:all'))

    return render(request, 'note/addNote.html', args)


@login_required(login_url='author:login')
def addCat(request, cat_id=None):

    args = {}
    user = get_user(request)
    args['categories'] = Categories.objects.filter(author=user.id)
    if cat_id:
        try:
            query = Categories.objects.get(id=cat_id, author=user.id)
        except Categories.DoesNotExist:
            return redirect(reverse('note:addCat'))
        args['form_category'] = AddCategoryForm(user.id, is_disabled=True, instance=query)
    else:
        query = None
        args['form_category'] = AddCategoryForm(user.id)

    args['cat_id'] = cat_id

    if request.POST:
        post_form = AddCategoryForm(user.id, data=request.POST, instance=query)
        if post_form.is_valid():
            post_form.save()
            return redirect(reverse('note:addCat'))

    return render(request, 'note/addCat.html', args)


@login_required(login_url='author:login')
def addTag(request, tag_id=None):

    args = {}
    user = get_user(request)
    args['tags'] = Tags.objects.filter(author=user.id)

    if tag_id:
        try:
            query = Tags.objects.get(id=tag_id, author=user.id)
        except Tags.DoesNotExist:
            return redirect(reverse('note:addTag'))
    else:
        query = None

    args['tag_id'] = tag_id
    args['form_tag'] = AddTagForm(user.id, instance=query)

    if request.POST:
        post_form = AddTagForm(user.id, data=request.POST, instance=query)
        if post_form.is_valid():
            post_form.save()

        return redirect(reverse('note:addTag'))

    return render(request, 'note/addTag.html', args)


@login_required(login_url='author:login')
def delNote(request, note_id):

    Notes.objects.get(pk=note_id).delete()

    return redirect(reverse('note:all'))


@login_required(login_url='author:login')
def delCat(request, cat_id):

    if request.POST:
        for cat_id in request.POST.getlist('remove_cat'):
            try:
                obj = Categories.objects.get(pk=cat_id)
                obj.delete()
            except Categories.DoesNotExist:
                continue

        return redirect(reverse('note:addCat'))
    else:
        Categories.objects.get(pk=cat_id).delete()

    return redirect(reverse('note:addCat'))


@login_required(login_url='author:login')
def delTag(request, tag_id):

    if request.POST:
        for tag_id in request.POST.getlist('remove_tag'):
            Tags.objects.get(pk=tag_id).delete()
        return redirect(reverse('note:addTag'))
    else:
        Tags.objects.get(pk=tag_id).delete()

    return redirect(reverse('note:addTag'))


def showCat(request, cat_id=None):
    user = get_user(request)
    args = {}
    args['notes'] = Notes.objects.filter(author=user.id, category=cat_id)

    return render(request, 'note/category.html', args)

reminder/note/templates/note/addCat.html
{% extends 'note/main_local.html' %}
{% load bootstrap3 %}
{% load mptt_tags %}

{% block categories %}

    <form action="
        {% if cat_id %}
            {% url 'note:editCat' cat_id %}
        {% else %}
            {% url 'note:addCat' %}
        {% endif %}
    " method="POST" class="form login_form">
        {% csrf_token %}

        <h1>{{ name }}</h1>
        {% bootstrap_form form_category %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
            </button>
        {% endbuttons %}

    </form>
    <hr>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Your Categories:</h3>
        </div>
        <form action="{% url 'note:delCat' 0 %}" method="POST">
            {% csrf_token %}
            {% buttons %}
                <button type="submit" class="btn btn-primary pull-right">
                    {% bootstrap_icon "remove" %} Delete
                </button>
            {% endbuttons %}
            <table class="table table-hover">
                <thead style="font-weight: bold;">
                <tr>
                    <td>#</td>
                    <td>Name</td>
                    <td>Subcategories</td>
                    <td>Parent category</td>
                    <td>Notes</td>
                </tr>
                </thead>
                <tbody>
                {% for category in categories %}
                    <tr>
                        <td><input type="checkbox" name="remove_cat" value="{{ category.id }}"></td>
                        <td><a href="{% url 'note:editCat' category.id %}">{{ category }}</a></td>
                        <td>{{ category.get_descendant_count }}</td>
                        <td>{{ category.parent|default:"---" }}</td>
                        <td>{{ category.notes_set.all|length }}</td>
                        <td><a href="{% url 'note:delCat' category.id %}" onclick="return confirm('Do you want to delete?');"><span class="glyphicon glyphicon-remove"></span></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>

    </div>

{% endblock %}

reminder/note/templates/note/addNote.html
{% extends 'note/main_local.html' %}
{% load bootstrap3 %}

{% block categories %}
    <form action="
    {% if note_id %}
        {% url 'note:editNote' note_id %}
    {% else %}
        {% url 'note:add' %}
    {% endif %} " method="POST" class="form login_form">
        {% csrf_token %}

        {% bootstrap_form form_note %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
            </button>
        {% endbuttons %}

    </form>

{% endblock %}

reminder/note/templates/note/addTag.html
{% extends 'note/main_local.html' %}
{% load bootstrap3 %}

{% block categories %}

    <form action="
        {% if tag_id %}
            {% url 'note:editTag' tag_id %}
        {% else %}
            {% url 'note:addTag' %}
        {% endif %}
    " method="POST" class="form login_form">
        {% csrf_token %}
        {% csrf_token %}

        {% bootstrap_form form_tag %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
            </button>
        {% endbuttons %}

    </form>


    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Your Tags:</h3>
        </div>
        <form action="{% url 'note:delTag' 0 %}" method="POST">
            {% csrf_token %}
            {% buttons %}
                <button type="submit" class="btn btn-primary pull-right">
                    {% bootstrap_icon "remove" %} Delete
                </button>
            {% endbuttons %}
            <table class="table table-hover">
                <thead style="font-weight: bold;">
                <tr>
                    <td>#</td>
                    <td>Name</td>
                    <td>Notes</td>
                </tr>
                </thead>
                <tbody>
                {% for tag in tags %}
                    <tr>
                        <td><input type="checkbox" name="remove_tag" value="{{ tag.id }}"></td>
                        <td><a href="{% url 'note:editTag' tag.id %}">{{ tag }}</a></td>
                        <td>{{ tag.notes_set.all|length }}</td>
                        <td><a href="{% url 'note:delTag' tag.id %}" onclick="return confirm('Do you want to delete?');"><span class="glyphicon glyphicon-remove"></span></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>

    </div>

{% endblock %}

reminder/note/templates/note/all.html
{% extends 'note/main_local.html' %}
{% load bootstrap3 %}
{% load mptt_tags %}

{% block categories %}

    <h1>This is a main page</h1>
    <hr>

    <div class="row">
        <div class="left col-md-3">
            {% if not categories %}
                <h3 style="color: gray; margin-top: 50px;">Categories not found</h3>
                <p>Click here to <a href="{% url 'note:addCat' %}">add new category</a></p>
            {% endif %}
            <ul style="list-style: none; font-size: 14px;">
                {% recursetree categories %}
                    <li>
                        <span class="glyphicon glyphicon-list-alt"></span> <a href="{% url 'note:showCat' node.id %}">{{ node.name }}</a>
                        <span style="font-size: 10px; background-color:tomato;" class="badge">{{ node.notes_set.all|length }}</span>
                        {% if not name.is_leaf_node %}
                            <ul style="list-style: none; margin-left: -20px;" class="children">
                                <a href="">{{ children }}</a>
                            </ul>
                        {% endif %}
                    </li>
                {% endrecursetree %}
            </ul>
        </div>

        <div class="right col-md-8 col-md-offset-1">
            <h2>My Notes: </h2>
            {% if not notes %}
                <h3 style="color: gray; margin-top: 50px;">Notes not found</h3>
                <p>Click here to <a href="{% url 'note:add' %}">add new note</a></p>
            {% endif %}
            {% for note in notes %}

                <p>
                    <a  role="button" data-toggle="collapse" href="#{{ note.id }}" aria-expanded="false" aria-controls="collapseExample">
                        {% if note.name %}
                            {{ note.name }}
                        {% else %}
                            no title
                        {% endif %}
                    </a>
                </p>

                <div class="collapse" id="{{ note.id }}">
                    <div class="well">
                        <a href="{% url 'note:editNote' note.id %}"><span class="glyphicon glyphicon-edit"></span></a>
                        <a href="{% url 'note:delNote' note.id %}" onclick="return confirm('Do you want to delete?');"><span class="glyphicon glyphicon-remove"></span></a>
                        <br>
                        <span style="background-color:{{ note.color }}; width: 10px; height: 10px; display: inline-block;"></span>
                        {{ note.context }}
                        {% if note.tag.all %}
                            <hr>
                            {% for tag in note.tag.all %}
                                <a href="{% url 'note:showTag' tag.id %}"><span class="glyphicon glyphicon glyphicon-tags"></span> {{ tag.name }}</a>
                            {% endfor %}
                        {% endif %}
                        {% if note.category.all %}<br>
                            <hr>
                            {% for category in note.category.all %}
                                <a href="{% url 'note:showCat' category.id %}">@ {{ category.name }}</a>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

            {% endfor %}

            {% for field in form %}
                <p>{{ field.label }}</p>
                <p>{{ field }}</p>
            {% endfor %}
        </div>
    </div>

    <hr>

{% endblock %}

reminder/note/templates/note/main_local.html
{% extends 'main.html' %}

{% block author_menu %}

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    {{ user.username|title }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'note:all' %}">Profile</a></li>
                    <li><a href="{% url 'note:add' %}">Add Note</a></li>
                    <li><a href="{% url 'note:addCat' %}">Categories</a></li>
                    <li><a href="{% url 'note:addTag' %}">Tags</a></li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="/auth/logout/">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                            Logout
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    {% block categories %}{% endblock %}
{% endblock %}