reminder/authorization/urls.py
from django.conf.urls import url

urlpatterns = [

    url(r'^login/$', 'authorization.views.login', name='login'),
    url(r'^registration/$', 'authorization.views.registration', name='regist'),
    url(r'^logout/$', 'authorization.views.logout', name='logout'),
]

reminder/note/urls.py
from django.conf.urls import url

urlpatterns = [

    url(r'^$', 'note.views.all', name='all'),

    url(r'^add/$', 'note.views.addNote', name='add'),
    url(r'^addCat/$', 'note.views.addCat', name='addCat'),
    url(r'^addTag/$', 'note.views.addTag', name='addTag'),

    url(r'^editTag/(?P<tag_id>[0-9]+)/$', 'note.views.addTag', name='editTag'),
    url(r'^edit/(?P<note_id>[0-9]+)/$', 'note.views.addNote', name='editNote'),
    url(r'^editCat/(?P<cat_id>[0-9]+)/$', 'note.views.addCat', name='editCat'),

    url(r'^delNote/(?P<note_id>[0-9]+)/$', 'note.views.delNote', name='delNote'),
    url(r'^delCat/(?P<cat_id>[0-9]+)/$', 'note.views.delCat', name='delCat'),
    url(r'^delTag/(?P<tag_id>[0-9]+)/$', 'note.views.delTag', name='delTag'),

    url(r'^cat(?P<cat_id>[0-9]+)/$', 'note.views.all', name='showCat'),
    url(r'^tag(?P<tag_id>[0-9]+)/$', 'note.views.all', name='showTag'),

]

reminder/reminder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'reminder.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^$', 'reminder.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('authorization.urls', namespace='author')),
    url(r'^note/', include('note.urls', namespace='note')),
    url(r'^$', 'note.views.all', name='home'),
]

reminder/authorization/models.py
from django.db import models

# Create your models here.

reminder/authorization/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()

        return user

reminder/authorization/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse

from .forms import UserCreateForm


def login(request):
    if request.user.is_authenticated():
        return redirect(reverse('note:all'))

    args = {}
    if request.POST:
        user_post_form = AuthenticationForm(request, data=request.POST)
        if user_post_form.is_valid():
            user = user_post_form.get_user()
            auth.login(request, user)
            return redirect(reverse('note:all'))
        else:
            args['login_error'] = 'User is not find'
            args['form'] = AuthenticationForm()
    else:
        args['form'] = AuthenticationForm()

    return render(request, 'authorization/login.html', args)


def logout(request):
    auth.logout(request)
    return redirect(reverse('author:login'))


def registration(request):
    if request.user.is_authenticated():
        return redirect(reverse('note:all'))

    args = {}
    if request.POST:
        user_post_form = UserCreateForm(request.POST)
        if user_post_form.is_valid():
            user_post_form.save()
            new_user = auth.authenticate(
                username=user_post_form.cleaned_data['username'],
                password=user_post_form.cleaned_data['password2']
            )
            auth.login(request, new_user)
            return redirect(reverse('note:all'))
        else:
            args['form'] = user_post_form
    else:
        args['form'] = UserCreateForm()

    return render(request, 'authorization/registr.html', args)

reminder/authorization/templates/authorization/login.html
{% extends 'authorization/main_local.html' %}

{% load staticfiles %}
{% load bootstrap3 %}


{% block local_css %}
    <link rel="stylesheet" href="{% static 'authorization/css/login.css' %}">
{% endblock %}


{% block content %}
    <div class="jumbotron">
            <h1>Hello world</h1>
            <form action="{% url 'author:login' %}" method="POST" class="form login_form">
                {% csrf_token %}

                {% if login_error %}
                    {% bootstrap_alert login_error alert_type='danger' %}
                {% endif %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Submit
                    </button>
                {% endbuttons %}

            </form>
    </div>
{% endblock %}

reminder/authorization/templates/authorization/main_local.html
{% extends 'main.html' %}

{% block author_menu %}
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'author:login' %}">
                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                    Login
                </a>
            </li>
            <li>
                <a href="{% url 'author:regist' %}">
                    <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                    Registration
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

reminder/authorization/templates/authorization/registr.html
{% extends 'authorization/main_local.html' %}

{% load staticfiles %}
{% load bootstrap3 %}

{% block local_css %}
    <link rel="stylesheet" href="{% static 'authorization/css/registr.css' %}">
{% endblock %}

{% block content %}
    <form action="{% url 'author:regist' %}" method="POST" class="form form_registr">
        {% csrf_token %}
        <div class="container">
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {% bootstrap_icon "star" %} Submit
                </button>
            {% endbuttons %}
        </div>
    </form>
{% endblock %}